/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedEnvironmentsRouteImport } from './routes/_authed/environments'
import { Route as AuthedEditorRouteImport } from './routes/_authed/editor'
import { Route as AuthedCustomersRouteImport } from './routes/_authed/customers'
import { Route as AuthedCustomerRouteImport } from './routes/_authed/_customer'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedCustomerSelectedAppRouteImport } from './routes/_authed/_customer/selectedApp'
import { Route as AuthedCustomerAppsRouteImport } from './routes/_authed/_customer/apps'
import { Route as AuthedCustomerSelectedAppLocalesRouteImport } from './routes/_authed/_customer/selectedApp/locales'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedEnvironmentsRoute = AuthedEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEditorRoute = AuthedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersRoute = AuthedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomerRoute = AuthedCustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCustomerSelectedAppRoute =
  AuthedCustomerSelectedAppRouteImport.update({
    id: '/selectedApp',
    path: '/selectedApp',
    getParentRoute: () => AuthedCustomerRoute,
  } as any)
const AuthedCustomerAppsRoute = AuthedCustomerAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthedCustomerRoute,
} as any)
const AuthedCustomerSelectedAppLocalesRoute =
  AuthedCustomerSelectedAppLocalesRouteImport.update({
    id: '/locales',
    path: '/locales',
    getParentRoute: () => AuthedCustomerSelectedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/customers': typeof AuthedCustomersRoute
  '/editor': typeof AuthedEditorRoute
  '/environments': typeof AuthedEnvironmentsRoute
  '/apps': typeof AuthedCustomerAppsRoute
  '/selectedApp': typeof AuthedCustomerSelectedAppRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/selectedApp/locales': typeof AuthedCustomerSelectedAppLocalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/customers': typeof AuthedCustomersRoute
  '/editor': typeof AuthedEditorRoute
  '/environments': typeof AuthedEnvironmentsRoute
  '/apps': typeof AuthedCustomerAppsRoute
  '/selectedApp': typeof AuthedCustomerSelectedAppRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/selectedApp/locales': typeof AuthedCustomerSelectedAppLocalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/_customer': typeof AuthedCustomerRouteWithChildren
  '/_authed/customers': typeof AuthedCustomersRoute
  '/_authed/editor': typeof AuthedEditorRoute
  '/_authed/environments': typeof AuthedEnvironmentsRoute
  '/_authed/_customer/apps': typeof AuthedCustomerAppsRoute
  '/_authed/_customer/selectedApp': typeof AuthedCustomerSelectedAppRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/_customer/selectedApp/locales': typeof AuthedCustomerSelectedAppLocalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/customers'
    | '/editor'
    | '/environments'
    | '/apps'
    | '/selectedApp'
    | '/api/auth/$'
    | '/selectedApp/locales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/customers'
    | '/editor'
    | '/environments'
    | '/apps'
    | '/selectedApp'
    | '/api/auth/$'
    | '/selectedApp/locales'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/_customer'
    | '/_authed/customers'
    | '/_authed/editor'
    | '/_authed/environments'
    | '/_authed/_customer/apps'
    | '/_authed/_customer/selectedApp'
    | '/api/auth/$'
    | '/_authed/_customer/selectedApp/locales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/environments': {
      id: '/_authed/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof AuthedEnvironmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/editor': {
      id: '/_authed/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthedEditorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers': {
      id: '/_authed/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedCustomersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_customer': {
      id: '/_authed/_customer'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedCustomerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_customer/selectedApp': {
      id: '/_authed/_customer/selectedApp'
      path: '/selectedApp'
      fullPath: '/selectedApp'
      preLoaderRoute: typeof AuthedCustomerSelectedAppRouteImport
      parentRoute: typeof AuthedCustomerRoute
    }
    '/_authed/_customer/apps': {
      id: '/_authed/_customer/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthedCustomerAppsRouteImport
      parentRoute: typeof AuthedCustomerRoute
    }
    '/_authed/_customer/selectedApp/locales': {
      id: '/_authed/_customer/selectedApp/locales'
      path: '/locales'
      fullPath: '/selectedApp/locales'
      preLoaderRoute: typeof AuthedCustomerSelectedAppLocalesRouteImport
      parentRoute: typeof AuthedCustomerSelectedAppRoute
    }
  }
}

interface AuthedCustomerSelectedAppRouteChildren {
  AuthedCustomerSelectedAppLocalesRoute: typeof AuthedCustomerSelectedAppLocalesRoute
}

const AuthedCustomerSelectedAppRouteChildren: AuthedCustomerSelectedAppRouteChildren =
  {
    AuthedCustomerSelectedAppLocalesRoute:
      AuthedCustomerSelectedAppLocalesRoute,
  }

const AuthedCustomerSelectedAppRouteWithChildren =
  AuthedCustomerSelectedAppRoute._addFileChildren(
    AuthedCustomerSelectedAppRouteChildren,
  )

interface AuthedCustomerRouteChildren {
  AuthedCustomerAppsRoute: typeof AuthedCustomerAppsRoute
  AuthedCustomerSelectedAppRoute: typeof AuthedCustomerSelectedAppRouteWithChildren
}

const AuthedCustomerRouteChildren: AuthedCustomerRouteChildren = {
  AuthedCustomerAppsRoute: AuthedCustomerAppsRoute,
  AuthedCustomerSelectedAppRoute: AuthedCustomerSelectedAppRouteWithChildren,
}

const AuthedCustomerRouteWithChildren = AuthedCustomerRoute._addFileChildren(
  AuthedCustomerRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCustomerRoute: typeof AuthedCustomerRouteWithChildren
  AuthedCustomersRoute: typeof AuthedCustomersRoute
  AuthedEditorRoute: typeof AuthedEditorRoute
  AuthedEnvironmentsRoute: typeof AuthedEnvironmentsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCustomerRoute: AuthedCustomerRouteWithChildren,
  AuthedCustomersRoute: AuthedCustomersRoute,
  AuthedEditorRoute: AuthedEditorRoute,
  AuthedEnvironmentsRoute: AuthedEnvironmentsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
