/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTasksRouteImport } from './routes/_authed/tasks'
import { Route as AuthedLocalesRouteImport } from './routes/_authed/locales'
import { Route as AuthedEnvironmentsRouteImport } from './routes/_authed/environments'
import { Route as AuthedEditorRouteImport } from './routes/_authed/editor'
import { Route as AuthedCustomersRouteImport } from './routes/_authed/customers'
import { Route as AuthedAppsRouteImport } from './routes/_authed/apps'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTasksRoute = AuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLocalesRoute = AuthedLocalesRouteImport.update({
  id: '/locales',
  path: '/locales',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEnvironmentsRoute = AuthedEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEditorRoute = AuthedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersRoute = AuthedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppsRoute = AuthedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/apps': typeof AuthedAppsRoute
  '/customers': typeof AuthedCustomersRoute
  '/editor': typeof AuthedEditorRoute
  '/environments': typeof AuthedEnvironmentsRoute
  '/locales': typeof AuthedLocalesRoute
  '/tasks': typeof AuthedTasksRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/apps': typeof AuthedAppsRoute
  '/customers': typeof AuthedCustomersRoute
  '/editor': typeof AuthedEditorRoute
  '/environments': typeof AuthedEnvironmentsRoute
  '/locales': typeof AuthedLocalesRoute
  '/tasks': typeof AuthedTasksRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authed/apps': typeof AuthedAppsRoute
  '/_authed/customers': typeof AuthedCustomersRoute
  '/_authed/editor': typeof AuthedEditorRoute
  '/_authed/environments': typeof AuthedEnvironmentsRoute
  '/_authed/locales': typeof AuthedLocalesRoute
  '/_authed/tasks': typeof AuthedTasksRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/apps'
    | '/customers'
    | '/editor'
    | '/environments'
    | '/locales'
    | '/tasks'
    | '/api/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/apps'
    | '/customers'
    | '/editor'
    | '/environments'
    | '/locales'
    | '/tasks'
    | '/api/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/logout'
    | '/_authed/apps'
    | '/_authed/customers'
    | '/_authed/editor'
    | '/_authed/environments'
    | '/_authed/locales'
    | '/_authed/tasks'
    | '/api/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tasks': {
      id: '/_authed/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/locales': {
      id: '/_authed/locales'
      path: '/locales'
      fullPath: '/locales'
      preLoaderRoute: typeof AuthedLocalesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/environments': {
      id: '/_authed/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof AuthedEnvironmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/editor': {
      id: '/_authed/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthedEditorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers': {
      id: '/_authed/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedCustomersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps': {
      id: '/_authed/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthedAppsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedAppsRoute: typeof AuthedAppsRoute
  AuthedCustomersRoute: typeof AuthedCustomersRoute
  AuthedEditorRoute: typeof AuthedEditorRoute
  AuthedEnvironmentsRoute: typeof AuthedEnvironmentsRoute
  AuthedLocalesRoute: typeof AuthedLocalesRoute
  AuthedTasksRoute: typeof AuthedTasksRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppsRoute: AuthedAppsRoute,
  AuthedCustomersRoute: AuthedCustomersRoute,
  AuthedEditorRoute: AuthedEditorRoute,
  AuthedEnvironmentsRoute: AuthedEnvironmentsRoute,
  AuthedLocalesRoute: AuthedLocalesRoute,
  AuthedTasksRoute: AuthedTasksRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
